/*
 * This file is generated by jOOQ.
*/
package com.onefactor.dsp.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Juser implements Serializable {

    private static final long serialVersionUID = 47876218;

    private final Integer       id;
    private final String        mail;
    private final String        password;
    private final String        firstName;
    private final String        lastName;
    private final Boolean       isDisabled;
    private final LocalDateTime createdAt;
    private final LocalDateTime lastLoginAt;
    private final Boolean       isRoleAdmin;
    private final Boolean       isActivated;

    public Juser(Juser value) {
        this.id = value.id;
        this.mail = value.mail;
        this.password = value.password;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.isDisabled = value.isDisabled;
        this.createdAt = value.createdAt;
        this.lastLoginAt = value.lastLoginAt;
        this.isRoleAdmin = value.isRoleAdmin;
        this.isActivated = value.isActivated;
    }

    public Juser(
        Integer       id,
        String        mail,
        String        password,
        String        firstName,
        String        lastName,
        Boolean       isDisabled,
        LocalDateTime createdAt,
        LocalDateTime lastLoginAt,
        Boolean       isRoleAdmin,
        Boolean       isActivated
    ) {
        this.id = id;
        this.mail = mail;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isDisabled = isDisabled;
        this.createdAt = createdAt;
        this.lastLoginAt = lastLoginAt;
        this.isRoleAdmin = isRoleAdmin;
        this.isActivated = isActivated;
    }

    public Integer getId() {
        return this.id;
    }

    public String getMail() {
        return this.mail;
    }

    public String getPassword() {
        return this.password;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public Boolean getIsDisabled() {
        return this.isDisabled;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    public Boolean getIsRoleAdmin() {
        return this.isRoleAdmin;
    }

    public Boolean getIsActivated() {
        return this.isActivated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Juser (");

        sb.append(id);
        sb.append(", ").append(mail);
        sb.append(", ").append(password);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(isDisabled);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastLoginAt);
        sb.append(", ").append(isRoleAdmin);
        sb.append(", ").append(isActivated);

        sb.append(")");
        return sb.toString();
    }
}
