/*
 * This file is generated by jOOQ.
*/
package com.onefactor.dsp.dao.jooq.tables.records;


import com.onefactor.dsp.dao.jooq.tables.Juser;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JuserRecord extends UpdatableRecordImpl<JuserRecord> implements Record10<Integer, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Boolean, Boolean> {

    private static final long serialVersionUID = -26772519;

    /**
     * Setter for <code>public.juser.id</code>.
     */
    public JuserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.juser.mail</code>.
     */
    public JuserRecord setMail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.mail</code>.
     */
    public String getMail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.juser.password</code>.
     */
    public JuserRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.juser.first_name</code>.
     */
    public JuserRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.juser.last_name</code>.
     */
    public JuserRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.juser.is_disabled</code>.
     */
    public JuserRecord setIsDisabled(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.is_disabled</code>.
     */
    public Boolean getIsDisabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.juser.created_at</code>.
     */
    public JuserRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.juser.last_login_at</code>.
     */
    public JuserRecord setLastLoginAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.last_login_at</code>.
     */
    public LocalDateTime getLastLoginAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.juser.is_role_admin</code>.
     */
    public JuserRecord setIsRoleAdmin(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.is_role_admin</code>.
     */
    public Boolean getIsRoleAdmin() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.juser.is_activated</code>.
     */
    public JuserRecord setIsActivated(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.juser.is_activated</code>.
     */
    public Boolean getIsActivated() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Boolean, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Boolean, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Juser.JUSER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Juser.JUSER.MAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Juser.JUSER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Juser.JUSER.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Juser.JUSER.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Juser.JUSER.IS_DISABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Juser.JUSER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Juser.JUSER.LAST_LOGIN_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Juser.JUSER.IS_ROLE_ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Juser.JUSER.IS_ACTIVATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getLastLoginAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsRoleAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getIsActivated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value2(String value) {
        setMail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value5(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value6(Boolean value) {
        setIsDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value8(LocalDateTime value) {
        setLastLoginAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value9(Boolean value) {
        setIsRoleAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord value10(Boolean value) {
        setIsActivated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JuserRecord values(Integer value1, String value2, String value3, String value4, String value5, Boolean value6, LocalDateTime value7, LocalDateTime value8, Boolean value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JuserRecord
     */
    public JuserRecord() {
        super(Juser.JUSER);
    }

    /**
     * Create a detached, initialised JuserRecord
     */
    public JuserRecord(Integer id, String mail, String password, String firstName, String lastName, Boolean isDisabled, LocalDateTime createdAt, LocalDateTime lastLoginAt, Boolean isRoleAdmin, Boolean isActivated) {
        super(Juser.JUSER);

        set(0, id);
        set(1, mail);
        set(2, password);
        set(3, firstName);
        set(4, lastName);
        set(5, isDisabled);
        set(6, createdAt);
        set(7, lastLoginAt);
        set(8, isRoleAdmin);
        set(9, isActivated);
    }
}
