/*
 * This file is generated by jOOQ.
*/
package com.onefactor.dsp.dao.jooq;


import com.onefactor.dsp.dao.jooq.tables.Databasechangeloglock;
import com.onefactor.dsp.dao.jooq.tables.Juser;
import com.onefactor.dsp.dao.jooq.tables.records.DatabasechangeloglockRecord;
import com.onefactor.dsp.dao.jooq.tables.records.JuserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JuserRecord, Integer> IDENTITY_JUSER = Identities0.IDENTITY_JUSER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> PK_DATABASECHANGELOGLOCK = UniqueKeys0.PK_DATABASECHANGELOGLOCK;
    public static final UniqueKey<JuserRecord> JUSER_PKEY = UniqueKeys0.JUSER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<JuserRecord, Integer> IDENTITY_JUSER = createIdentity(Juser.JUSER, Juser.JUSER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DatabasechangeloglockRecord> PK_DATABASECHANGELOGLOCK = createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "pk_databasechangeloglock", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
        public static final UniqueKey<JuserRecord> JUSER_PKEY = createUniqueKey(Juser.JUSER, "juser_pkey", Juser.JUSER.ID);
    }
}
