/*
 * This file is generated by jOOQ.
*/
package com.onefactor.dsp.dao.jooq;


import com.onefactor.dsp.dao.jooq.tables.Databasechangelog;
import com.onefactor.dsp.dao.jooq.tables.Databasechangeloglock;
import com.onefactor.dsp.dao.jooq.tables.Juser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.onefactor.dsp.dao.jooq.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.onefactor.dsp.dao.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.juser</code>.
     */
    public static final Juser JUSER = com.onefactor.dsp.dao.jooq.tables.Juser.JUSER;
}
